### ISSUE TITLE
toolbar ['SImage']

### ISSUE THREAD

**Issue by chbro** [upgrad/ckeditor-image-uploader-plugin#3]
you seem to forget telling  me to add '**SImage**' in the toolbar config

**Comment by asthas** [comment]
@chbro Thanks for pointing out. I have updated the README.md.

**Comment by Dev-Int** [comment]
Hi @chbro , the add is done, but can you be more clear on the case: '_**SI**mage_', not '_**si**mage_' in the README.md ?
